files:
  - source: /en/*.md
    translation: /%locale%/%original_file_name%
    languages_mapping:
      locale:
        zh-CN: zh-cn
        el: el-gr
        ru: ru-ru
        es-ES: es-es
        uk: uk-ua
